version: '3.8'
services: 
  api:
    container_name: api-container
    restart: always
    build: ./server
    ports: 
      - "5000:5000"
  client:
    container_name: client-container
    restart: always
    build: ./wildfire-project-ui
    ports: 
      - "8080:8080"
    depends_on: 
      - api